// Deterministic pre-submission scrubber (PRD M3). Ten rule families; each issue carries rule,
// severity, field and fix. Rules decide; AI never overrides a blocking rule.
import { EXCLUSIVE_PAIRS, lookupCode } from "../data/codeset.ts";
import { authRequired, payerById } from "../data/reference.ts";
import type { Claim, Patient, PriorAuth, ScrubIssue } from "../domain/types.ts";
import { ageOn, daysBetween, sha256 } from "../util.ts";
import { validateClaimXml } from "../xml/claim-xml.ts";
import { contractPrice } from "./pricing.ts";

export interface ScrubContext {
  patient: Patient;
  priorAuths: PriorAuth[];
  /** Other claims already submitted (for duplicate detection). */
  otherClaims: Pick<Claim, "id" | "patientId" | "serviceDate" | "activities" | "status">[];
  today: string;
  /** Optional XML to schema-check (generated by the caller). */
  xml?: string;
}

export interface ScrubResult {
  issues: ScrubIssue[];
  score: number;
  denialRisk: number;
}

export const RULE_FAMILIES = [
  "eligibility",
  "authorisation",
  "code_validity",
  "code_pairing",
  "demographic",
  "pricing",
  "duplicates",
  "timeliness",
  "completeness",
  "schema",
] as const;

const WEIGHT = { blocking: 22, warning: 4 };

export function scrubClaim(claim: Claim, ctx: ScrubContext): ScrubResult {
  const issues: ScrubIssue[] = [];
  // Stable ids (rule + field) so an issue keeps its id across re-scrubs.
  const add = (issue: Omit<ScrubIssue, "id">) =>
    issues.push({ id: `iss_${sha256(`${issue.rule}|${issue.field}`).slice(0, 12)}`, ...issue });
  const payer = payerById(claim.payerId);
  const { patient } = ctx;

  // 1. Eligibility
  if (claim.serviceDate < patient.coverageStart || claim.serviceDate > patient.coverageEnd)
    add({
      rule: "ELIG-ACTIVE",
      family: "eligibility",
      severity: "blocking",
      field: "Claim.MemberID",
      message: `Member ${patient.memberId} coverage ${patient.coverageStart} to ${patient.coverageEnd} does not include the service date ${claim.serviceDate}.`,
      fix: "Run an eligibility check; update the member ID/payer or bill the patient as self-pay.",
    });
  if (patient.payerId !== claim.payerId)
    add({
      rule: "ELIG-PAYER",
      family: "eligibility",
      severity: "blocking",
      field: "Claim.PayerID",
      message: `Claim payer ${payer.name} does not match the patient's insurer on file.`,
      fix: "Correct the payer on the claim.",
      autoFix: { kind: "set_payer", value: patient.payerId },
    });

  // 2. Authorisation (one issue per rule, listing every affected activity)
  const approvedFor = (code: string) =>
    ctx.priorAuths.filter(
      (p) =>
        p.status === "approved" &&
        p.payerId === claim.payerId &&
        p.patientId === claim.patientId &&
        p.services.some((s) => s.code === code) &&
        (!p.validUntil || p.validUntil >= claim.serviceDate),
    );
  const needsAuth = claim.activities.filter((a) => authRequired(payer, a.code));
  const missing = needsAuth.filter((a) => !a.priorAuthNumber);
  const mismatched = needsAuth.filter(
    (a) => a.priorAuthNumber && !approvedFor(a.code).some((p) => p.approvalNumber === a.priorAuthNumber),
  );
  const authFix = (list: typeof missing) => {
    const numbers = list.map((a) => approvedFor(a.code)[0]?.approvalNumber);
    return numbers.every(Boolean)
      ? { kind: "attach_auth", value: Object.fromEntries(list.map((a, i) => [a.id, numbers[i]])) }
      : undefined;
  };
  if (missing.length) {
    const fix = authFix(missing);
    const found = [...new Set(missing.map((a) => approvedFor(a.code)[0]?.approvalNumber).filter(Boolean))];
    add({
      rule: "AUTH-REQUIRED",
      family: "authorisation",
      severity: "blocking",
      field: `Activity[${missing.map((a) => a.code).join(", ")}].PriorAuthorizationID`,
      message: `${payer.name} requires prior approval for ${missing.map((a) => a.code).join(", ")} and no approval number is attached.`,
      fix: fix
        ? `Attach approved authorisation ${found.join(", ")} found in the prior-auth workbench.`
        : "Request prior approval from the Eligibility & Prior auth workbench before submitting.",
      autoFix: fix,
    });
  }
  if (mismatched.length) {
    const fix = authFix(mismatched);
    add({
      rule: "AUTH-MATCH",
      family: "authorisation",
      severity: "blocking",
      field: `Activity[${mismatched.map((a) => a.code).join(", ")}].PriorAuthorizationID`,
      message: `Approval number on ${mismatched.map((a) => a.code).join(", ")} is not an approved, in-date authorisation for this patient and service.`,
      fix: fix ? "Replace with the matching approved authorisation." : "Verify the approval number with the payer.",
      autoFix: fix,
    });
  }

  // 3. Code validity
  for (const d of claim.diagnoses) {
    const entry = lookupCode(d.code);
    if (!entry || entry.type !== "ICD10" || !entry.active)
      add({
        rule: "CODE-VALID-DX",
        family: "code_validity",
        severity: "blocking",
        field: `Diagnosis[${d.code}]`,
        message: entry && !entry.active ? `${d.code} is inactive: ${entry.description}.` : `${d.code} is not a valid ICD-10-CM code in the loaded code set.`,
        fix: d.code === "M54.5" ? "Replace with M54.50 (Low back pain, unspecified)." : "Choose an active, valid ICD-10-CM code.",
        autoFix: d.code === "M54.5" ? { kind: "replace_dx", value: { from: "M54.5", to: "M54.50" } } : undefined,
      });
  }
  for (const a of claim.activities) {
    const entry = lookupCode(a.code);
    if (!entry || !entry.active || entry.type === "ICD10")
      add({
        rule: "CODE-VALID-ACT",
        family: "code_validity",
        severity: "blocking",
        field: `Activity[${a.code}].Code`,
        message: `${a.code} is not a valid active procedure/drug code.`,
        fix: "Choose a valid code from the code set.",
      });
    else if (entry.type !== a.codeType)
      add({
        rule: "CODE-TYPE",
        family: "code_validity",
        severity: "blocking",
        field: `Activity[${a.code}].Type`,
        message: `${a.code} is a ${entry.type} code but is submitted as ${a.codeType}.`,
        fix: `Set the activity type to ${entry.type}.`,
        autoFix: { kind: "set_code_type", activityId: a.id, value: entry.type },
      });
  }
  if (!claim.diagnoses.some((d) => d.type === "principal"))
    add({
      rule: "CODE-PRINCIPAL",
      family: "code_validity",
      severity: "blocking",
      field: "Diagnosis",
      message: "The claim has no principal diagnosis.",
      fix: "Mark one diagnosis as principal.",
    });

  // 4. Code pairing (medical necessity + mutually exclusive procedures)
  const dxCodes = claim.diagnoses.map((d) => d.code);
  for (const a of claim.activities) {
    const entry = lookupCode(a.code);
    if (!entry?.supportedBy?.length) continue;
    const supported = dxCodes.some((dx) => entry.supportedBy?.some((prefix) => dx.startsWith(prefix)));
    if (!supported)
      add({
        rule: "PAIR-NECESSITY",
        family: "code_pairing",
        severity: "blocking",
        field: `Activity[${a.code}]`,
        message: `No diagnosis on the claim supports ${a.code} (${entry.description}). Expected a diagnosis in ${entry.supportedBy.join(", ")}.`,
        fix: "Add the diagnosis that supports this service, or remove the service.",
      });
  }
  const codes = new Set(claim.activities.map((a) => a.code));
  for (const [x, y, why] of EXCLUSIVE_PAIRS)
    if (codes.has(x) && codes.has(y))
      add({
        rule: "PAIR-EXCLUSIVE",
        family: "code_pairing",
        severity: "blocking",
        field: `Activity[${y}]`,
        message: `${x} and ${y} billed together: ${why}.`,
        fix: `Remove ${y} or document a distinct session.`,
        autoFix: { kind: "remove_activity", activityId: claim.activities.find((a) => a.code === y)?.id },
      });

  // 5. Demographic edits
  const age = ageOn(patient.dob, claim.serviceDate);
  for (const code of [...dxCodes, ...claim.activities.map((a) => a.code)]) {
    const entry = lookupCode(code);
    if (!entry) continue;
    if (entry.gender && entry.gender !== patient.gender)
      add({
        rule: "DEMO-GENDER",
        family: "demographic",
        severity: "blocking",
        field: `Code[${code}]`,
        message: `${code} applies only to ${entry.gender === "F" ? "female" : "male"} patients; patient is ${patient.gender === "F" ? "female" : "male"}.`,
        fix: "Check the patient's gender on registration or correct the code.",
      });
    if ((entry.minAge !== undefined && age < entry.minAge) || (entry.maxAge !== undefined && age > entry.maxAge))
      add({
        rule: "DEMO-AGE",
        family: "demographic",
        severity: "blocking",
        field: `Code[${code}]`,
        message: `${code} is not valid for a ${age}-year-old.`,
        fix: "Use the age-appropriate code.",
      });
  }

  // 6. Pricing
  for (const a of claim.activities) {
    const unit = a.quantity > 0 ? a.gross / a.quantity : a.gross;
    const agreed = contractPrice(claim.payerId, a.code);
    if (agreed > 0 && unit > agreed + 0.005)
      add({
        rule: "PRICE-CONTRACT",
        family: "pricing",
        severity: "blocking",
        field: `Activity[${a.code}].Gross`,
        message: `AED ${unit.toFixed(2)} per unit exceeds the ${payer.name} contract price of AED ${agreed.toFixed(2)} for ${a.code}.`,
        fix: `Bill at the contract price (AED ${agreed.toFixed(2)}).`,
        autoFix: { kind: "set_price", activityId: a.id, value: agreed },
      });
  }

  // 7. Duplicates
  for (const other of ctx.otherClaims) {
    if (other.id === claim.id || other.patientId !== claim.patientId || other.serviceDate !== claim.serviceDate) continue;
    if (["draft", "scrubbed", "written_off", "rejected"].includes(other.status)) continue;
    for (const a of claim.activities)
      if (other.activities.some((o) => o.code === a.code))
        add({
          rule: "DUP-ACTIVITY",
          family: "duplicates",
          severity: "blocking",
          field: `Activity[${a.code}]`,
          message: `${a.code} for this patient on ${claim.serviceDate} was already submitted on claim ${other.id}.`,
          fix: "Remove the duplicate activity or void this claim.",
          autoFix: { kind: "remove_activity", activityId: a.id },
        });
  }

  // 8. Timeliness
  const age0 = daysBetween(claim.serviceDate, ctx.today);
  if (age0 > payer.submissionWindowDays)
    add({
      rule: "TIME-WINDOW",
      family: "timeliness",
      severity: "blocking",
      field: "Encounter.Start",
      message: `Service was ${age0} days ago; ${payer.name} accepts first submissions within ${payer.submissionWindowDays} days.`,
      fix: "Submit only with proof of timely filing; otherwise write off.",
    });
  else if (age0 > payer.submissionWindowDays - 10)
    add({
      rule: "TIME-NEAR",
      family: "timeliness",
      severity: "warning",
      field: "Encounter.Start",
      message: `Only ${payer.submissionWindowDays - age0} days left in the ${payer.name} submission window.`,
      fix: "Prioritise submission today.",
    });

  // 9. Completeness
  if (!claim.clinicianLicence)
    add({
      rule: "COMP-CLINICIAN",
      family: "completeness",
      severity: "blocking",
      field: "Activity.Clinician",
      message: "Clinician licence is missing; the gateway rejects activities without it.",
      fix: "Fill the ordering clinician's licence from the encounter.",
      autoFix: { kind: "fill_clinician" },
    });
  if (!claim.encounterType)
    add({
      rule: "COMP-ENCTYPE",
      family: "completeness",
      severity: "blocking",
      field: "Encounter.Type",
      message: "Encounter type is missing.",
      fix: "Set the encounter type (outpatient for clinic visits).",
      autoFix: { kind: "set_encounter_type", value: "outpatient" },
    });
  if (!patient.emiratesIdEnc)
    add({
      rule: "COMP-EID",
      family: "completeness",
      severity: "blocking",
      field: "Claim.EmiratesIDNumber",
      message: "Emirates ID is missing on the patient record.",
      fix: "Capture the Emirates ID at registration.",
    });
  if (!claim.activities.length)
    add({
      rule: "COMP-ACTIVITY",
      family: "completeness",
      severity: "blocking",
      field: "Activity",
      message: "The claim has no activities.",
      fix: "Add at least one billed service.",
    });
  if (claim.activities.some((a) => a.quantity <= 0))
    add({
      rule: "COMP-QTY",
      family: "completeness",
      severity: "blocking",
      field: "Activity.Quantity",
      message: "Every activity needs a quantity of at least 1.",
      fix: "Set quantity to 1 or more.",
    });
  // A code-level documentation hint: physio without an evaluation on record for new episodes.
  if (claim.specialty === "Physiotherapy" && claim.activities.length > 0 && !claim.activities.some((a) => a.code.startsWith("9716")) && claim.activities.length >= 3)
    add({
      rule: "DOC-PT-PLAN",
      family: "completeness",
      severity: "warning",
      field: "Attachments",
      message: "Three or more physiotherapy units without an evaluation code; payers often ask for the treatment plan.",
      fix: "Attach the physiotherapy plan of care.",
    });

  // 10. Schema
  if (ctx.xml) {
    const errors = validateClaimXml(ctx.xml);
    for (const e of errors.slice(0, 5))
      add({
        rule: "SCHEMA",
        family: "schema",
        severity: "blocking",
        field: e.path,
        message: `XML schema: ${e.message}`,
        fix: "Correct the field so the claim validates against the pinned DHA claim schema.",
      });
  }

  const penalty = issues.reduce((sum, i) => sum + WEIGHT[i.severity], 0);
  const score = Math.max(0, Math.min(100, 100 - penalty));
  // Predicted denial risk: blocking issues dominate; a small payer baseline remains.
  const blocking = issues.filter((i) => i.severity === "blocking").length;
  const baseline = { payer_nahr: 0.09, payer_saffron: 0.12, payer_gulf: 0.06 }[claim.payerId] ?? 0.08;
  const denialRisk = Math.min(0.97, blocking ? 0.55 + 0.12 * (blocking - 1) : baseline + (100 - score) / 400);
  return { issues, score, denialRisk: Number(denialRisk.toFixed(2)) };
}

